import type { Metadata } from "next";
import Image from "next/image";
import { Header } from "@/components/header";
import { Footer } from "@/components/home";
import { FinalCta, Process, VisualHero } from "@/components/content-page";
import { SectionHeading } from "@/components/ui";
import { consultationDetails, consultationPoints } from "@/data/site";

export const metadata: Metadata = { title: "Expert Logistics Consultation", description: "Practical advisory for supply chain design, warehouse planning, cost control and logistics transformation.", alternates: { canonical: "/expert-consultation" } };

export default function ExpertConsultationPage() { return <><Header /><main>
  <VisualHero eyebrow="Core solution" title="Expert Logistics Consultation" text="Professional advisory services designed to optimize end-to-end supply chain operations, improve efficiency and reduce logistics costs." image="/images/expert-consultation/expert-consultation-hero.png" primary="Speak to a Logistics Consultant" secondary="Explore Our Expertise" />
  <section id="services" className="section-pad bg-white"><div className="container-shell grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><SectionHeading eyebrow="Practical advisory" title="From operational challenges to practical solutions" text="Consultation starts with the operation as it exists today: the flow of goods, the information people use, the constraints on site and the priorities that shape service. We review those realities before identifying improvement opportunities. Recommendations are intended to be practical, with consideration for implementation sequence, people, technology and the decisions a business needs to make." /><p className="mt-5 leading-8 text-text-muted">The aim is to give leaders and operations teams a clearer basis for improving cost, capacity, consistency and service level over time.</p></div><div className="relative aspect-[4/3] overflow-hidden rounded-[20px]"><Image src="/images/expert-consultation/logistics-planning-review.png" alt="Logistics planning review" fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover" /></div></div></section>
  <section className="section-pad bg-soft"><div className="container-shell"><SectionHeading eyebrow="Our consulting expertise" title="A connected view of supply chain performance" /><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{consultationPoints.map((point, index) => <article key={point} className="rounded-[16px] border border-border bg-white p-6"><span className="text-xs font-extrabold tracking-[.14em] text-brand">{String(index + 1).padStart(2, "0")}</span><h2 className="mt-3 text-lg font-extrabold text-primary">{point}</h2><p className="mt-3 text-sm leading-6 text-text-muted">{consultationDetails[index]}</p></article>)}</div></div></section>
  <section className="section-pad bg-white"><div className="container-shell grid items-center gap-10 lg:grid-cols-2"><div className="relative aspect-[4/3] overflow-hidden rounded-[20px]"><Image src="/images/expert-consultation/warehouse-planning.png" alt="Warehouse operations planning" fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover" /></div><div><SectionHeading eyebrow="Connected decisions" title="Strategy, systems and facility planning" text="Supply chain strategy works best when it connects high-level decisions to the conditions on the warehouse floor and in the transport network. A layout decision can affect picking travel, equipment use and delivery timing; a technology decision needs to reflect the information teams actually need. Consultation helps bring these dependencies into a single conversation." /><p className="mt-5 leading-8 text-text-muted">Whether reviewing an established operation or planning a new facility, the work can clarify priorities before resources are committed. For ongoing operational execution, explore our <a href="/reliable-solutions" className="font-bold text-brand hover:text-primary">Reliable Solutions</a> approach.</p></div></div></section>
  <Process title="Our consulting process" steps={[{ title: "Discover", text: "Understand the current operation, goals and constraints." }, { title: "Assess", text: "Review processes, costs, information and operating dependencies." }, { title: "Design", text: "Develop practical improvement opportunities and scenarios." }, { title: "Plan", text: "Define priorities, sequencing and implementation considerations." }, { title: "Support", text: "Assist with implementation and continuing operational improvement." }]} />
  <FinalCta title="Ready to turn logistics insight into action?" text="Speak with our team about your supply chain, warehouse, transportation or facility planning requirements." />
</main><Footer /></>; }
