import type { Metadata } from "next";
import { Header } from "@/components/header";
import { Footer } from "@/components/home";
import { PageHero, SectionHeading } from "@/components/ui";

export const metadata: Metadata = { title: "About Us", description: "Learn how LogiSmart Solutions designs intelligent, reliable logistics operations across Saudi Arabia." };

export default function AboutPage() { return <><Header /><main><PageHero eyebrow="About Us" title="About LogiSmart Solutions" text="At LogiSmart Solutions Company, we believe that successful logistics extends beyond the movement and storage of goods. It is about creating intelligent supply chain strategies that drive business performance and sustainable growth." /><section className="section-pad bg-white"><div className="container-shell grid gap-10 lg:grid-cols-[1.1fr_0.9fr]"><div><SectionHeading title="A partner for smarter operations" text="We bring together practical logistics experience, dependable delivery systems, and expert advice for businesses operating across Saudi Arabia." /><p className="mt-6 leading-8 text-text-muted">Our core focus is clear: smart logistics, reliable solutions, and expert consultation that make operations easier to manage and stronger over time.</p></div><div className="grid gap-5"><Info title="Our Vision" text="To be the logistics partner of choice in Saudi Arabia, known for innovation, reliability, and exceptional customer-focused solutions that drive sustainable growth and excellence." /><Info title="Our Mission" text="To empower businesses through smart logistics solutions, delivering reliable and efficient services as a trusted partner, supported by expert consultation that drives operational excellence and sustainable growth." /></div></div></section><section className="bg-soft py-16"><div className="container-shell max-w-4xl text-center"><p className="text-2xl font-extrabold leading-9 text-primary md:text-3xl">At LogiSmart Solutions, we do not just move goods. We design smarter logistics, deliver reliable solutions, and provide expert consultation that drives business success.</p></div></section></main><Footer /></>; }
function Info({ title, text }: { title: string; text: string }) { return <article className="rounded-[16px] border border-border bg-white p-6"><h2 className="text-xl font-extrabold text-primary">{title}</h2><p className="mt-3 leading-7 text-text-muted">{text}</p></article>; }
