import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { ButtonLink, SectionHeading } from "@/components/ui";

export function VisualHero({ eyebrow, title, text, image, primary = "Request Consultation", secondary = "Explore Services" }: { eyebrow: string; title: string; text: string; image: string; primary?: string; secondary?: string }) {
  return <section className="overflow-hidden bg-soft"><div className="container-shell grid items-stretch gap-10 py-12 md:py-16 lg:grid-cols-[.92fr_1.08fr] lg:py-20"><div className="flex flex-col justify-center"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-brand">{eyebrow}</p><h1 className="mt-4 max-w-xl text-4xl font-extrabold leading-[1.08] text-primary md:text-6xl">{title}</h1><p className="mt-5 max-w-xl text-base leading-8 text-text-muted md:text-lg">{text}</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/contact">{primary}<ArrowRight size={16} /></ButtonLink><ButtonLink href="#services" variant="secondary">{secondary}</ButtonLink></div></div><div className="relative min-h-[310px] overflow-hidden rounded-[24px] bg-primary md:min-h-[440px]"><Image src={image} alt="Logistics operations" fill priority sizes="(min-width:1024px) 55vw, 100vw" className="object-cover" /></div></div></section>;
}

export function Process({ title = "How We Work", steps }: { title?: string; steps: { title: string; text: string }[] }) {
 return <section className="section-pad bg-soft"><div className="container-shell"><SectionHeading eyebrow="Our approach" title={title} /><div className="mt-10 grid gap-px overflow-hidden rounded-[20px] border border-border bg-border md:grid-cols-5">{steps.map((step, index) => <div key={step.title} className="bg-soft p-6"><span className="text-xs font-extrabold tracking-[.16em] text-brand">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-3 font-extrabold text-primary">{step.title}</h3><p className="mt-2 text-sm leading-6 text-text-muted">{step.text}</p></div>)}</div></div></section>;
}

export function FinalCta({ title, text }: { title: string; text: string }) { return <section className="bg-primary py-16 text-white md:py-20"><div className="container-shell flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-accent">Let&apos;s plan it</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold md:text-5xl">{title}</h2><p className="mt-4 max-w-2xl leading-7 text-white/70">{text}</p></div><ButtonLink href="/contact" className="!bg-accent !text-primary hover:!bg-white">Contact Our Team <ArrowRight size={16} /></ButtonLink></div></section>; }

export function ServiceSection({ item, index }: { item: { title: string; description: string; points: readonly string[]; image: string; copy: string }; index: number }) { return <section id={item.title.toLowerCase().replaceAll(/[^a-z0-9]+/g, "-")} className={`scroll-mt-24 section-pad ${index % 2 ? "bg-soft" : "bg-white"}`}><div className="container-shell grid items-center gap-10 lg:grid-cols-2"><div className={`relative aspect-[4/3] overflow-hidden rounded-[20px] bg-primary ${index % 2 ? "lg:order-2" : ""}`}><Image src={item.image} alt={item.title} fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover" /></div><div><span className="text-sm font-extrabold tracking-[.14em] text-brand">{String(index + 1).padStart(2, "0")}</span><h2 className="mt-3 text-3xl font-extrabold text-primary md:text-4xl">{item.title}</h2><p className="mt-5 leading-8 text-text-muted">{item.copy}</p><ul className="mt-6 grid gap-3">{item.points.map(point => <li key={point} className="flex gap-3 text-sm leading-6 text-text-muted"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-brand" />{point}</li>)}</ul><Link href="/contact" className="mt-7 inline-flex items-center gap-2 text-sm font-extrabold text-brand hover:text-primary">Enquire About This Service <ArrowRight size={16} /></Link></div></div></section>; }
