"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Mail, MapPin, Phone, Send } from "lucide-react";
import { motion, useReducedMotion, useScroll } from "framer-motion";
import { FormEvent, useState } from "react";
import { advantageCards, contactDetails, insights, services } from "@/data/site";
import { BrandLogo } from "@/components/header";
import { ButtonLink, SectionHeading } from "@/components/ui";
import { ContactForm } from "@/components/contact-form";
import { ShipmentJourney } from "@/components/shipment-journey";

const fade = { hidden: { opacity: 0, y: 22 }, show: { opacity: 1, y: 0 } };
function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { const reduce = useReducedMotion(); return <motion.div className={className} variants={reduce ? undefined : fade} initial={reduce ? false : "hidden"} whileInView={reduce ? undefined : "show"} viewport={{ once: true, margin: "-60px" }} transition={{ duration: 0.5, ease: "easeOut" }}>{children}</motion.div>; }

export function HomePage() { return <main><ScrollProgress /><Hero /><StatsStrip /><Introduction /><ServicesGrid /><ShipmentJourney /><Consultation /><ValueSection /><Advantages /><Sectors /><Credibility /><Team /><ContactSection /><Insights /><Newsletter /></main>; }

function ScrollProgress() {
  const reduce = useReducedMotion();
  const { scrollYProgress } = useScroll();
  return <motion.div aria-hidden="true" className="fixed inset-x-0 top-0 z-[70] h-1 origin-left bg-accent" style={{ scaleX: reduce ? 0 : scrollYProgress }} />;
}

function Hero() {
  return <section aria-label="Logistics operations video" className="relative h-[min(78svh,780px)] min-h-[440px] overflow-hidden bg-primary-deep">
    <video autoPlay muted loop playsInline preload="auto" disablePictureInPicture poster="/logismart-hero-poster.jpg" className="absolute inset-0 h-full w-full object-cover">
      <source src="/logismart-hero.mp4" type="video/mp4" />
    </video>
  </section>;
}

function StatsStrip() { const items = [["01", "Nationwide Network"], ["02", "Integrated Solutions"], ["03", "Customer-Focused Operations"]]; return <section className="relative z-10 -mt-8"><div className="container-shell grid overflow-hidden rounded-[16px] border border-border bg-white shadow-[var(--shadow-card)] md:grid-cols-3">{items.map(([number, label]) => <div key={number} className="flex items-center gap-4 border-b border-border p-6 last:border-b-0 md:border-b-0 md:border-r last:md:border-r-0"><span className="text-3xl font-extrabold text-brand">{number}</span><p className="text-sm font-extrabold text-primary">{label}</p></div>)}</div></section>; }

function Introduction() { return <section className="section-pad bg-surface"><div className="container-shell grid items-center gap-12 lg:grid-cols-[0.9fr_1fr]"><Reveal className="relative min-h-[440px] overflow-hidden rounded-[20px]"><Image src="/images/logistics/13_about_ship_variant_2.png" alt="Logistics infrastructure supporting Saudi business operations" fill sizes="(min-width:1024px) 48vw, 100vw" className="object-cover" /></Reveal><Reveal><SectionHeading eyebrow="About LogiSmart" title="Smart Logistics Built Around Your Business" text="At LogiSmart Solutions Company, we believe successful logistics extends beyond moving and storing goods. It is about creating intelligent supply chain strategies that improve business performance, operational efficiency, and sustainable growth." /><p className="mt-5 leading-8 text-text-muted">Through advanced technology, data-driven planning, and industry expertise, we provide integrated logistics support across freight forwarding, transportation, customs clearance, warehousing, packing, moving, equipment rental, and supply chain consultation.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><Feature title="Smart Logistics" text="Advanced tools, real-time visibility, and optimized operations." /><Feature title="Reliable Solutions" text="Consistent service quality, dependable execution, and business continuity." /></div><ButtonLink href="/about" className="mt-8">Learn More</ButtonLink></Reveal></div></section>; }
function Feature({ title, text }: { title: string; text: string }) { return <div className="border-l-2 border-brand bg-white p-5"><h3 className="font-extrabold text-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-text-muted">{text}</p></div>; }

function ServicesGrid() { return <section id="services" className="section-pad bg-white"><div className="container-shell"><Reveal><SectionHeading eyebrow="Our Services" title="End-to-End Logistics Solutions" text="Comprehensive logistics services powered by technology, expertise, and a commitment to operational excellence." /></Reveal><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((service) => { const Icon = service.icon; return <Reveal key={service.title}><Link href="/smart-logistics" className="group flex h-full flex-col rounded-[16px] border border-border bg-white p-7 shadow-[var(--shadow-card)] transition hover:-translate-y-1 hover:border-brand"><Icon className="text-brand" size={31} /><h3 className="mt-7 text-2xl font-extrabold text-primary">{service.title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-text-muted">{service.description}</p><span className="mt-6 flex items-center gap-2 text-sm font-extrabold text-brand">Learn More <ArrowRight size={16} className="transition group-hover:translate-x-1" /></span></Link></Reveal>; })}</div></div></section>; }

function Consultation() { const [status, setStatus] = useState<"idle" | "loading" | "success">("idle"); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { form.reportValidity(); return; } setStatus("loading"); window.setTimeout(() => { form.reset(); setStatus("success"); }, 700); } return <section className="section-pad bg-soft"><div className="container-shell grid overflow-hidden rounded-[20px] border border-border bg-white lg:grid-cols-[0.82fr_1.18fr]"><div className="relative min-h-[420px]"><Image src="/images/logistics/04_quote_team_variant_1.png" alt="Logistics professionals discussing operational requirements" fill sizes="(min-width:1024px) 43vw, 100vw" className="object-cover" /></div><form noValidate onSubmit={submit} className="grid gap-5 p-6 md:p-10"><SectionHeading eyebrow="Request a Consultation" title="Plan Your Next Logistics Solution" text="Tell us about your operational requirements and our team will help identify the right logistics solution for your business." /><div className="grid gap-4 md:grid-cols-2"><Input label="Full Name" required /><Input label="Company Name" required /><Input label="Email Address" type="email" required /><Input label="Phone Number" required /><label className="grid gap-2 text-sm font-bold text-primary"><span>Service Required</span><select className="field" required defaultValue=""><option value="" disabled>Select a service</option>{services.map((item) => <option key={item.title}>{item.title}</option>)}<option>Reliable Solutions</option><option>Expert Consultation</option></select></label><Input label="Origin" /><Input label="Destination" /></div><label className="grid gap-2 text-sm font-bold text-primary"><span>Message</span><textarea className="field min-h-28" required placeholder="Tell us about your requirements." /></label><button disabled={status === "loading"} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-brand px-5 text-sm font-extrabold text-white hover:bg-primary disabled:opacity-70">{status === "loading" ? "Sending..." : "Request Consultation"} <Send size={17} /></button>{status === "success" ? <p role="status" className="text-sm font-bold text-brand">Thank you. Your consultation request has been received.</p> : null}</form></div></section>; }
function Input({ label, type = "text", required = false }: { label: string; type?: string; required?: boolean }) { return <label className="grid gap-2 text-sm font-bold text-primary"><span>{label}</span><input className="field" required={required} type={type} /></label>; }

function ValueSection() { const items = [["01", "Smart Logistics", "Technology-enabled planning, real-time visibility, and optimized logistics operations."], ["02", "Reliable Solutions", "Consistent execution, accurate processes, and dependable service performance."], ["03", "Expert Consultation", "Strategic logistics advice that improves efficiency, compliance, and cost control."], ["04", "Customer-Focused Support", "Flexible solutions tailored to each client’s operational requirements."]]; return <section className="bg-primary px-4 py-12"><div className="container-shell relative overflow-hidden rounded-[20px] bg-[linear-gradient(130deg,#16865F,#0D332B_58%,#09251F)] p-8 text-white md:p-12"><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full border-[44px] border-accent/20" /><div className="relative grid gap-10 lg:grid-cols-[0.94fr_1.06fr]"><div><p className="text-xs font-extrabold tracking-[0.18em] text-accent">WHY LOGISMART</p><h2 className="mt-4 text-4xl font-extrabold leading-tight md:text-6xl">Smart Operations.<br />Reliable Delivery.<br />Sustainable Growth.</h2><p className="mt-5 max-w-xl leading-8 text-white/75">We combine technology, operational expertise, and customer-focused planning to deliver dependable logistics solutions that support long-term business success.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/smart-logistics" className="bg-white !text-primary hover:bg-soft">Explore Solutions</ButtonLink><ButtonLink href="/contact" variant="secondary" className="border-white/25 bg-white/5 text-white">Contact Our Team</ButtonLink></div></div><div className="grid gap-3 sm:grid-cols-2">{items.map(([number, title, text]) => <div key={number} className="border border-white/15 bg-primary-deep/25 p-5"><p className="text-2xl font-extrabold text-accent">{number}</p><h3 className="mt-3 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/70">{text}</p></div>)}</div></div></div></section>; }

function Advantages() { return <section className="section-pad bg-white"><div className="container-shell"><SectionHeading eyebrow="Our Advantage" title="Why Businesses Choose LogiSmart" align="center" /><div className="mt-12 grid items-center gap-7 lg:grid-cols-[1fr_0.9fr_1fr]"><div className="grid gap-5">{advantageCards.slice(0, 3).map((item) => <Advantage key={item.title} {...item} />)}</div><Reveal className="relative min-h-[500px] overflow-hidden rounded-[20px]"><Image src="/images/logistics/16_topdown_ship_variant_2.png" alt="Overhead view of a logistics operation" fill sizes="(min-width:1024px) 32vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-primary/15" /></Reveal><div className="grid gap-5">{advantageCards.slice(3).map((item) => <Advantage key={item.title} {...item} />)}</div></div></div></section>; }
function Advantage({ title, description, icon: Icon }: (typeof advantageCards)[number]) { return <Reveal className="border-l-2 border-brand bg-soft p-5"><Icon size={24} className="text-brand" /><h3 className="mt-3 font-extrabold text-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-text-muted">{description}</p></Reveal>; }

function Sectors() { const sectors = ["Importers", "Manufacturers", "Distributors", "Retailers", "E-Commerce", "Industrial Businesses"]; return <section className="border-y border-border bg-soft py-16"><div className="container-shell"><SectionHeading title="Supporting Businesses Across Key Sectors" align="center" /><div className="mt-9 grid gap-px overflow-hidden rounded-[14px] border border-border bg-border sm:grid-cols-2 lg:grid-cols-6">{sectors.map((sector) => <div key={sector} className="grid min-h-28 place-items-center bg-white px-4 text-center text-sm font-extrabold text-primary">{sector}</div>)}</div></div></section>; }

function Credibility() { return <section className="section-pad bg-primary-deep text-white"><div className="container-shell grid items-center gap-12 lg:grid-cols-[0.9fr_1fr]"><Reveal className="relative min-h-[470px] overflow-hidden rounded-[20px]"><Image src="/images/logistics/17_testimonial_worker_variant_2.png" alt="Logistics professional overseeing a cargo operation" fill sizes="(min-width:1024px) 46vw, 100vw" className="object-cover" /></Reveal><Reveal><p className="text-xs font-extrabold tracking-[0.18em] text-accent">TRUSTED LOGISTICS PARTNER</p><h2 className="mt-4 text-4xl font-extrabold leading-tight md:text-5xl">Built Around Reliability, Precision, and Performance</h2><p className="mt-5 leading-8 text-white/72">LogiSmart Solutions supports importers, manufacturers, distributors, retailers, e-commerce businesses, and industrial organizations with integrated logistics operations tailored to evolving market requirements.</p><p className="mt-4 leading-8 text-white/72">Our team combines industry knowledge, standardized processes, technology-driven tools, and responsive customer support to help clients operate smarter and grow with confidence.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{["End-to-End Support", "Technology-Driven Operations", "Customer-Focused Service"].map((item) => <div key={item} className="border border-white/15 p-4 text-sm font-extrabold text-accent">{item}</div>)}</div><ButtonLink href="/about" className="mt-8">About LogiSmart</ButtonLink></Reveal></div></section>; }

function Team() { const team = [
  { role: "Operations Manager", image: "/images/logistics/logismart-team-member-01.webp" },
  { role: "Logistics Consultant", image: "/images/logistics/logismart-team-member-02.webp" },
  { role: "Customer Support Lead", image: "/images/logistics/logismart-team-member-03.webp" }
]; return <section className="section-pad bg-surface"><div className="container-shell"><SectionHeading eyebrow="Our People" title="People Behind the Movement" text="Our logistics professionals bring together operational expertise, strategic insight, and customer-focused service to deliver effective solutions." align="center" /><div className="mt-12 grid gap-5 md:grid-cols-3">{team.map((member) => <Reveal key={member.role} className="overflow-hidden rounded-[16px] border border-border bg-white shadow-[var(--shadow-card)]"><div className="relative aspect-square bg-soft"><Image src={member.image} alt={`${member.role} at LogiSmart Solutions`} fill sizes="(min-width:768px) 31vw, 100vw" className="object-cover" /></div><div className="p-6 text-center"><h3 className="text-xl font-extrabold text-primary">{member.role}</h3><p className="mt-2 text-sm text-text-muted">LogiSmart Solutions</p></div></Reveal>)}</div></div></section>; }

function ContactSection() { return <section className="section-pad bg-white"><div className="container-shell grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><Reveal><SectionHeading eyebrow="Contact Us" title="Talk to a Logistics Specialist" text="Share your logistics requirements with our team and discover a solution designed around your business." /><div className="mt-8 grid gap-4 text-sm leading-6 text-text-muted"><p className="flex gap-3"><MapPin className="shrink-0 text-brand" size={18} />{contactDetails.address}</p><a href="tel:+966502964915" className="flex gap-3 hover:text-brand"><Phone className="shrink-0 text-brand" size={18} />{contactDetails.phonePrimary}</a><a href="tel:+966557818795" className="flex gap-3 hover:text-brand"><Phone className="shrink-0 text-brand" size={18} />{contactDetails.phoneSecondary}</a><a href="mailto:support@logismart.me" className="flex gap-3 hover:text-brand"><Mail className="shrink-0 text-brand" size={18} />{contactDetails.email}</a></div></Reveal><Reveal><ContactForm /></Reveal></div></section>; }

function Insights() { return <section className="section-pad bg-soft"><div className="container-shell"><SectionHeading eyebrow="Insights" title="Latest Logistics Thinking" /><div className="mt-11 grid gap-5 lg:grid-cols-3">{insights.map((article) => <Reveal key={article.title}><article className="h-full overflow-hidden rounded-[16px] border border-border bg-white shadow-[var(--shadow-card)]"><div className="relative aspect-[1.4/1]"><Image src={article.image} alt="" fill sizes="(min-width:1024px) 31vw, 100vw" className="object-cover" /></div><div className="p-6"><p className="text-xs font-extrabold tracking-[0.1em] text-brand">{article.category}</p><h3 className="mt-3 text-xl font-extrabold text-primary">{article.title}</h3><p className="mt-3 text-sm leading-6 text-text-muted">{article.description}</p></div></article></Reveal>)}</div><ButtonLink href="#" variant="secondary" className="mt-8">View All Insights</ButtonLink></div></section>; }

function Newsletter() { const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); return <section className="bg-primary px-4 py-12 text-white"><div className="container-shell grid items-center gap-6 rounded-[18px] bg-brand p-7 md:grid-cols-[1fr_0.86fr] md:p-10"><div><h2 className="text-3xl font-extrabold md:text-4xl">Get Logistics Insights in Your Inbox</h2><p className="mt-3 text-sm leading-6 text-white/75">Occasional practical guidance. No unnecessary email.</p></div><form onSubmit={(event) => { event.preventDefault(); if (email) setSent(true); }} className="grid gap-3 sm:grid-cols-[1fr_auto]"><input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email Address" className="min-h-12 rounded-md border border-white/25 bg-white/10 px-4 text-white placeholder:text-white/65 outline-none focus:border-accent" /><button className="min-h-12 rounded-md bg-white px-6 text-sm font-extrabold text-primary hover:bg-soft">Subscribe</button>{sent ? <p role="status" className="text-sm text-accent sm:col-span-2">Thank you. You&apos;re subscribed to LogiSmart insights.</p> : null}</form></div></section>; }

export function Footer() { return <footer className="bg-primary-deep text-white"><div className="container-shell grid gap-10 py-14 lg:grid-cols-[1.25fr_0.75fr]"><div><BrandLogo dark /><p className="mt-5 max-w-xl text-sm leading-7 text-white/70">Smart logistics, reliable solutions, and expert consultation designed to drive operational excellence and sustainable growth.</p></div><div><h2 className="text-sm font-extrabold tracking-[0.12em] text-accent">CONTACT</h2><div className="mt-4 grid gap-3 text-sm leading-6 text-white/70"><p>{contactDetails.address}</p><a href="tel:+966502964915" className="hover:text-accent">{contactDetails.phonePrimary}</a><a href="tel:+966557818795" className="hover:text-accent">{contactDetails.phoneSecondary}</a><a href="mailto:support@logismart.me" className="hover:text-accent">{contactDetails.email}</a><a href={contactDetails.website} className="hover:text-accent">www.logismart.me</a></div></div></div><div className="border-t border-white/10"><div className="container-shell py-5 text-sm text-white/50">Copyright 2026 LogiSmart Solutions. All rights reserved.</div></div></footer>; }
