import type { Metadata } from "next";
import Image from "next/image";
import { Header } from "@/components/header";
import { Footer } from "@/components/home";
import { FinalCta, Process, ServiceSection, VisualHero } from "@/components/content-page";
import { SectionHeading } from "@/components/ui";
import { serviceDetails } from "@/data/site";

export const metadata: Metadata = { title: "Smart Logistics", description: "Integrated freight, transport, customs, warehousing, handling and equipment support across Saudi Arabia.", alternates: { canonical: "/smart-logistics" } };
export default function SmartLogisticsPage() { return <><Header /><main><VisualHero eyebrow="Core solution" title="Smart Logistics" text="Technology-supported logistics processes that connect freight, transport, customs, warehousing and operational equipment into a practical, coordinated approach across Saudi Arabia." image="/images/smart-logistics/smart-logistics-hero.png" /><section className="section-pad bg-white"><div className="container-shell grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><SectionHeading eyebrow="Integrated operations" title="From origin to destination" text="LogiSmart brings the moving parts of an operation together: cargo booking, land movement, documentation, storage, handling, equipment support and warehouse infrastructure. Instead of treating each requirement in isolation, we help teams plan the handovers between them. That means a freight movement can be considered alongside clearance preparation, delivery timing, available storage and the equipment required on site. The result is a clearer operational picture for importers, manufacturers, distributors and industrial businesses." /></div><div className="relative aspect-[4/3] overflow-hidden rounded-[20px]"><Image src="/images/logistics/16_topdown_ship_variant_2.png" alt="Coordinated cargo operations" fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover" /></div></div></section><div id="services">{serviceDetails.map((item, index) => <ServiceSection key={item.slug} item={item} index={index} />)}</div><Process steps={[{ title: "Understand Requirements", text: "Review cargo, site conditions, timing and operating priorities." }, { title: "Plan the Operation", text: "Connect the right services, documents, equipment and handovers." }, { title: "Coordinate & Execute", text: "Keep responsibilities clear through each stage of movement." }, { title: "Monitor Progress", text: "Use status updates and communication to keep work visible." }, { title: "Support & Improve", text: "Review exceptions and evolving needs as the operation continues." }]} /><FinalCta title="Need an Integrated Logistics Solution?" text="Tell us about your cargo, transportation, warehousing or operational requirements and our team can help identify a suitable logistics approach." /></main><Footer /></>; }
